# Generated by Django 4.0.3 on 2022-03-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='is_logedin',
            field=models.BooleanField(default=False),
        ),
    ]
